name: "Feature Request"
description: Create a new ticket for a new feature request
title: "[REQUEST] - <title>"
labels: [ "request" ]
body:
  - type: textarea
    id: description
    attributes:
      label: "Description"
      description: Provide a brief explanation of the request.
      placeholder: Describe in a few lines your feature request.
    validations:
      required: true
  - type: textarea
    id: code_example
    attributes:
      label: "Code Example"
      description: Indicate here some basic examples of your feature.
      placeholder: A few specific lines of code for your feature request.