import kotlin.String

/**
 * Generated by
 *    $ ./gradlew buildSrcLibs
 * Re-run when you add a new dependency to the build
 *
 * Find which updates are available by running
 *     $ ./gradlew refreshVersions
 * And edit the file `versions.properties`
 *
 * See https://github.com/jmfayard/refreshVersions
 */
public object Libs {
    public const val activity_compose: String = "androidx.activity:activity-compose:_"

    public const val core_testing: String = "androidx.arch.core:core-testing:_"

    public const val androidx_compose_compiler_compiler: String =
            "androidx.compose.compiler:compiler:_"

    public const val material3: String = "androidx.compose.material3:material3:_"

    public const val androidx_compose_runtime_runtime: String = "androidx.compose.runtime:runtime:_"

    public const val ui_tooling: String = "androidx.compose.ui:ui-tooling:_"

    public const val ui_tooling_preview: String = "androidx.compose.ui:ui-tooling-preview:_"

    public const val constraintlayout: String = "androidx.constraintlayout:constraintlayout:_"

    public const val databinding_adapters: String = "androidx.databinding:databinding-adapters:_"

    public const val databinding_common: String = "androidx.databinding:databinding-common:_"

    public const val databinding_compiler: String = "androidx.databinding:databinding-compiler:_"

    public const val databinding_ktx: String = "androidx.databinding:databinding-ktx:_"

    public const val databinding_runtime: String = "androidx.databinding:databinding-runtime:_"

    public const val viewbinding: String = "androidx.databinding:viewbinding:_"

    public const val hilt_compiler: String = "androidx.hilt:hilt-compiler:_"

    public const val hilt_navigation_compose: String = "androidx.hilt:hilt-navigation-compose:_"

    public const val lifecycle_viewmodel_compose: String =
            "androidx.lifecycle:lifecycle-viewmodel-compose:_"

    public const val navigation_compose: String = "androidx.navigation:navigation-compose:_"

    public const val navigation_safe_args_gradle_plugin: String =
            "androidx.navigation:navigation-safe-args-gradle-plugin:_"

    public const val room_compiler: String = "androidx.room:room-compiler:_"

    public const val room_ktx: String = "androidx.room:room-ktx:_"

    public const val room_runtime: String = "androidx.room:room-runtime:_"

    public const val swiperefreshlayout: String = "androidx.swiperefreshlayout:swiperefreshlayout:_"

    public const val espresso_contrib: String = "androidx.test.espresso:espresso-contrib:_"

    public const val espresso_core: String = "androidx.test.espresso:espresso-core:_"

    public const val junit_ktx: String = "androidx.test.ext:junit-ktx:_"

    public const val core_ktx: String = "androidx.test:core-ktx:_"

    public const val androidx_test_rules: String = "androidx.test:rules:_"

    public const val androidx_test_runner: String = "androidx.test:runner:_"

    public const val work_runtime_ktx: String = "androidx.work:work-runtime-ktx:_"

    public const val com_android_tools_build_gradle: String = "com.android.tools.build:gradle:_"

    public const val accompanist_swiperefresh: String =
            "com.google.accompanist:accompanist-swiperefresh:_"

    public const val play_services_ads: String = "com.google.android.gms:play-services-ads:_"

    public const val hilt_android: String = "com.google.dagger:hilt-android:_"

    public const val hilt_android_compiler: String = "com.google.dagger:hilt-android-compiler:_"

    public const val hilt_android_gradle_plugin: String =
            "com.google.dagger:hilt-android-gradle-plugin:_"

    public const val firebase_analytics_ktx: String = "com.google.firebase:firebase-analytics-ktx"

    public const val firebase_appdistribution_gradle: String =
            "com.google.firebase:firebase-appdistribution-gradle:_"

    public const val firebase_bom: String = "com.google.firebase:firebase-bom:_"

    public const val firebase_crashlytics_gradle: String =
            "com.google.firebase:firebase-crashlytics-gradle:_"

    public const val firebase_crashlytics_ktx: String =
            "com.google.firebase:firebase-crashlytics-ktx"

    public const val firebase_messaging_ktx: String = "com.google.firebase:firebase-messaging-ktx"

    public const val google_services: String = "com.google.gms:google-services:_"

    public const val core_bom: String = "com.htecgroup.core:bom:_"

    public const val `data`: String = "com.htecgroup.core:data"

    public const val domain: String = "com.htecgroup.core:domain"

    public const val presentation: String = "com.htecgroup.core:presentation"

    public const val presentation_databinding: String =
            "com.htecgroup.core:presentation-databinding"

    public const val test: String = "com.htecgroup.core:test"

    public const val moshi_kotlin_codegen: String = "com.squareup.moshi:moshi-kotlin-codegen:_"

    public const val logging_interceptor: String = "com.squareup.okhttp3:logging-interceptor:_"

    public const val de_fayard_buildsrclibs_gradle_plugin: String =
            "de.fayard.buildSrcLibs:de.fayard.buildSrcLibs.gradle.plugin:_"

    public const val android_junit5: String = "de.mannodermaus.gradle.plugins:android-junit5:_"

    public const val detekt_formatting: String = "io.gitlab.arturbosch.detekt:detekt-formatting:_"

    public const val io_gitlab_arturbosch_detekt_gradle_plugin: String =
            "io.gitlab.arturbosch.detekt:io.gitlab.arturbosch.detekt.gradle.plugin:_"

    public const val mockk: String = "io.mockk:mockk:_"

    public const val kluent_android: String = "org.amshove.kluent:kluent-android:_"

    public const val org_jacoco_ant: String = "org.jacoco:org.jacoco.ant:_"

    public const val kotlin_annotation_processing_gradle: String =
            "org.jetbrains.kotlin:kotlin-annotation-processing-gradle:_"

    public const val kotlin_gradle_plugin: String = "org.jetbrains.kotlin:kotlin-gradle-plugin:_"

    public const val kotlin_parcelize_compiler: String =
            "org.jetbrains.kotlin:kotlin-parcelize-compiler:_"

    public const val kotlin_parcelize_runtime: String =
            "org.jetbrains.kotlin:kotlin-parcelize-runtime:_"

    public const val kotlin_stdlib: String = "org.jetbrains.kotlin:kotlin-stdlib:_"

    public const val kotlinx_coroutines_android: String =
            "org.jetbrains.kotlinx:kotlinx-coroutines-android:_"

    public const val kotlinx_coroutines_core: String =
            "org.jetbrains.kotlinx:kotlinx-coroutines-core:_"

    public const val kotlinx_coroutines_test: String =
            "org.jetbrains.kotlinx:kotlinx-coroutines-test:_"

    public const val junit_jupiter_api: String = "org.junit.jupiter:junit-jupiter-api:_"

    public const val junit_jupiter_engine: String = "org.junit.jupiter:junit-jupiter-engine:_"

    public const val junit_jupiter_params: String = "org.junit.jupiter:junit-jupiter-params:_"

    public const val junit_vintage_engine: String = "org.junit.vintage:junit-vintage-engine:_"

    public const val robolectric: String = "org.robolectric:robolectric:_"
}
