name: Snapshot

on:
  pull_request:
    types: [ opened, synchronize ]
    branches:
      - main
    paths-ignore:
      - 'sample/**'

jobs:
  snapshot:
    if: startsWith(github.event.pull_request.head.ref, 'bump-')
    runs-on: ubuntu-latest
    env:
      BOM_VERSION_SUFFIX: -SNAPSHOT
      SIGNING_KEY_ID: ${{ secrets.SIGNING_KEY_ID }}
      SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
      SIGNING_SECRET_KEY_RING_FILE: '../signing/SecretRingKey.gpg'
      OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
      OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
      SONATYPE_STAGING_PROFILE_ID: ${{ secrets.SONATYPE_STAGING_PROFILE_ID }}
    steps:
      - name: Setup java
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: zulu

      - name: Code checkout
        uses: actions/checkout@v3

      - name: Code style check
        run: ./gradlew detekt

      - name: Set version output
        id: set_version_output
        run: ./gradlew setVersionOutput

      - name: Print version
        run: echo ${{ steps.set_version_output.outputs.BOM_VERSION }}

      - name: Generate secret key
        run: |
          mkdir ./signing
          echo ${{ secrets.SIGNING_KEY }} | base64 --decode > ./signing/SecretRingKey.gpg
          mkdir ./sample/app/signing
          echo ${{ secrets.KEYSTORE_PROPERTIES }} | base64 --decode > ./sample/app/signing/keystore.properties
          echo ${{ secrets.RELEASE_KEYSTORE }} | base64 --decode > ./sample/app/signing/release-keystore.jks

      - name: Build release
        run: ./gradlew assembleRelease

      - name: Publish snapshot
        run: ./gradlew publishAllPublicationsToSonatypeRepository