name: Snapshot

on:
  pull_request:
    types: [ opened, synchronize ]
    branches:
      - main
    paths-ignore:
      - 'sample/**'

jobs:
  snapshot:
    if: startsWith(github.event.pull_request.head.ref, 'bump-')
    runs-on: ubuntu-latest
    env:
      BOM_VERSION_SUFFIX: -SNAPSHOT
    steps:
      - name: Setup java
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: temurin

      - name: Code checkout
        uses: actions/checkout@v3

      - name: Code style check
        run: ./gradlew detekt

      - name: Set version output
        id: set_version_output
        run: ./gradlew setVersionOutput

      - name: Print version
        run: echo ${{ steps.set_version_output.outputs.BOM_VERSION }}

      - name: Build release
        run: ./gradlew assembleRelease

      - name: Publish snapshot
        run: ./gradlew publish